""" This script saves things to your computer! it will generate a folder in
    it's current directory with a time stamp, and generate some artwork in
    it, as well as give you some deets about the back end of the generation
    (in the form of .txt files. You can specify your own rgb color values as
    well. The color palet I have at the bottom of the file right now is
    generated by color.adobe.com's triad color rule, which I have darkened.
"""

import random
from PIL import Image
from tqdm import *


def test_image(filename, x_size=350, y_size=350):
    """ Generate test image with random pixels and save as an image file.

        filename: string filename for image (should be .png)
        x_size, y_size: optional args to set image dimensions (default: 350)
    """
    # Create image and loop over all pixels
    im = Image.new("RGB", (x_size, y_size))
    pixels = im.load()
    for i in tqdm(range(x_size)):
        for j in range(y_size):
            # x = remap_interval(i, 0, x_size, -1, 1)
            # y = remap_interval(j, 0, y_size, -1, 1)
            pixels[i, j] = (random.randint(0, 255),  # Red channel
                            random.randint(0, 255),  # Green channel
                            random.randint(0, 255))  # Blue channel

    im.save(filename)

if __name__ == '__main__':
    dir = "out/"
    filepath = dir + "noise.png"
    test_image(filepath, 1400, 1000)

